module.exports = [ { name: 'MojomFile',
    bnf: [ [ 'StatementList' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'StatementList',
    bnf: [ [ 'Statement*' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Statement',
    bnf: 
     [ [ 'ModuleStatement' ],
       [ 'ImportStatement' ],
       [ 'Definition' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'ModuleStatement',
    bnf: 
     [ [ 'AttributeSection?', '"module"', 'WS+', 'Identifier', '";"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'ImportStatement',
    bnf: [ [ '"import"', 'WS+', 'StringLiteral', '";"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Definition',
    bnf: 
     [ [ 'Struct' ],
       [ 'Union' ],
       [ 'Interface' ],
       [ 'Enum' ],
       [ 'Const' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'AttributeSection',
    bnf: [ [ '"["', 'AttributeList', '"]"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%%AttributeList01',
    bnf: [ [ '","', 'Attribute' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: '%AttributeList0',
    bnf: [ [ 'Attribute', '%%AttributeList01*' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'AttributeList',
    bnf: [ [ '%AttributeList0?' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%%Attribute23',
    bnf: [ [ 'Name' ], [ 'Literal' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: '%Attribute2',
    bnf: [ [ '"="', '%%Attribute23' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'Attribute',
    bnf: [ [ 'Name', '%Attribute2?' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%Struct4',
    bnf: [ [ '"{"', 'StructBody', '"}"' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'Struct',
    bnf: 
     [ [ 'AttributeSection?', '"struct"', 'Name', '%Struct4?', '";"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%StructBody5',
    bnf: [ [ 'Const' ], [ 'Enum' ], [ 'StructField' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'StructBody',
    bnf: [ [ '%StructBody5*' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'StructField',
    bnf: 
     [ [ 'AttributeSection?',
         'TypeSpec',
         'Name',
         'Ordinal?',
         'Default?',
         '";"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Union',
    bnf: 
     [ [ 'AttributeSection?',
         '"union"',
         'Name',
         '"{"',
         'UnionField*',
         '"}"',
         '";"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'UnionField',
    bnf: 
     [ [ 'AttributeSection?', 'TypeSpec', 'Name', 'Ordinal?', '";"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Interface',
    bnf: 
     [ [ 'AttributeSection?',
         '"interface"',
         'Name',
         '"{"',
         'InterfaceBody?',
         '"}"',
         '";"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%InterfaceBody6',
    bnf: [ [ 'Const' ], [ 'Enum' ], [ 'Method' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'InterfaceBody',
    bnf: [ [ '%InterfaceBody6*' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Method',
    bnf: 
     [ [ 'AttributeSection?',
         'Name',
         'Ordinal?',
         '"("',
         'ParameterList?',
         '")"',
         'Response?',
         '";"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%%ParameterList78',
    bnf: [ [ '","', 'Parameter' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: '%ParameterList7',
    bnf: [ [ 'Parameter', '%%ParameterList78*' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'ParameterList',
    bnf: [ [ '%ParameterList7' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Parameter',
    bnf: [ [ 'AttributeSection?', 'TypeSpec', 'Name', 'Ordinal?' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%Response9',
    bnf: [ [ '"=>"', '"("', 'ParameterList', '")"' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'Response',
    bnf: [ [ '%Response9' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'TypeSpec',
    bnf: [ [ 'TypeName', 'Nullable?' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Nullable',
    bnf: [ [ '"?"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Associated',
    bnf: [ [ '"associated"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'TypeName',
    bnf: 
     [ [ 'Array' ],
       [ 'FixedArray' ],
       [ 'Map' ],
       [ 'InterfaceRequest' ],
       [ 'BasicTypeName' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'BasicTypeName',
    bnf: 
     [ [ 'HandleType' ],
       [ 'NumericType' ],
       [ 'Associated?', 'Identifier' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'NumericType',
    bnf: 
     [ [ '"bool"' ],
       [ '"int8"' ],
       [ '"uint8"' ],
       [ '"int16"' ],
       [ '"uint16"' ],
       [ '"int32"' ],
       [ '"uint32"' ],
       [ '"int64"' ],
       [ '"uint64"' ],
       [ '"float"' ],
       [ '"double"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%HandleType10',
    bnf: [ [ '"<"', 'SpecificHandleType', '">"' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'HandleType',
    bnf: [ [ '"handle"', '%HandleType10?' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'SpecificHandleType',
    bnf: 
     [ [ '"message_pipe"' ],
       [ '"shared_buffer"' ],
       [ '"data_pipe_consumer"' ],
       [ '"data_pipe_producer"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Array',
    bnf: [ [ '"array"', '"<"', 'TypeSpec', '">"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'FixedArray',
    bnf: 
     [ [ '"array"', '"<"', 'TypeSpec', '","', 'IntConstDec', '">"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Map',
    bnf: [ [ '"map"', '"<"', 'Identifier', '","', 'TypeSpec', '">"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'InterfaceRequest',
    bnf: [ [ 'Associated?', 'Identifier', '"&"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%Default11',
    bnf: [ [ '"="', 'Constant' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'Default',
    bnf: [ [ '%Default11?' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Enum',
    bnf: 
     [ [ 'AttributeSection?',
         '"enum"',
         'Name',
         '"{"',
         'NonEmptyEnumValueList',
         '","?',
         '"}"',
         '";"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%%NonEmptyEnumValueList1213',
    bnf: [ [ '","', 'EnumValue' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: '%NonEmptyEnumValueList12',
    bnf: [ [ 'EnumValue', '%%NonEmptyEnumValueList1213*' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'NonEmptyEnumValueList',
    bnf: [ [ '%NonEmptyEnumValueList12' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%%EnumValue1415',
    bnf: [ [ 'Integer' ], [ 'Identifier' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: '%EnumValue14',
    bnf: [ [ '"="', '%%EnumValue1415' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'EnumValue',
    bnf: [ [ 'AttributeSection?', 'Name', '%EnumValue14?' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Const',
    bnf: [ [ '"const"', 'TypeSpec', 'Name', '"="', 'Constant', '";"' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Constant',
    bnf: [ [ 'Literal' ], [ 'Identifier' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%%Identifier1617',
    bnf: [ [ '"."', 'Name' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: '%Identifier16',
    bnf: [ [ 'Name', '%%Identifier1617*' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'Identifier',
    bnf: [ [ '%Identifier16' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Literal',
    bnf: 
     [ [ 'Integer' ],
       [ 'Float' ],
       [ '"true"' ],
       [ '"false"' ],
       [ '"default"' ],
       [ 'StringLiteral' ] ],
    implicitWs: true,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Integer',
    bnf: [ [ 'IntConst' ], [ '"+"', 'IntConst' ], [ '"-"', 'IntConst' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'IntConst',
    bnf: [ [ 'IntConstDec' ], [ 'IntConstHex' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'Float',
    bnf: 
     [ [ 'FloatConst' ],
       [ '"+"', 'FloatConst' ],
       [ '"-"', 'FloatConst' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%Name18', bnf: [ [ /[0-9a-zA-Z_]/ ] ], pinned: false },
  { name: 'Name',
    bnf: [ [ /[a-zA-Z_]/, '%Name18*' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%IntConstDec19', bnf: [ [ /[0-9]/ ] ], pinned: false },
  { name: 'IntConstDec',
    bnf: [ [ '"0"' ], [ /[1-9]/, '%IntConstDec19*' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%IntConstHex20',
    bnf: [ [ /[0-9a-fA-F]/ ] ],
    pinned: false },
  { name: 'IntConstHex',
    bnf: [ [ '"0"', /[xX]/, '%IntConstHex20+' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%%%Ordinal212223', bnf: [ [ /[0-9]/ ] ], pinned: false },
  { name: '%%Ordinal2122',
    bnf: [ [ /[1-9]/, '%%%Ordinal212223*' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: '%Ordinal21',
    bnf: [ [ '"0"' ], [ '%%Ordinal2122' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'Ordinal',
    bnf: [ [ '"@"', '%Ordinal21' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%EOL24', bnf: [ [ /[\x0A\x0D]/ ] ], pinned: false },
  { name: 'EOL',
    bnf: [ [ '%EOL24+' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%%Comment2526',
    bnf: [ [ /[\x0A\x0D]/ ] ],
    pinned: false },
  { name: '%Comment25',
    bnf: [ [ '!%%Comment2526', /[\x00-\uFFFF]/ ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'Comment',
    bnf: [ [ '\'//\'', '%Comment25*', 'EOL' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%WS27',
    bnf: [ [ /[\x20\x09\x0A\x0D]/ ] ],
    pinned: false },
  { name: 'WS',
    bnf: [ [ 'Comment' ], [ '%WS27+' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%FloatConst28',
    bnf: [ [ '"0"' ], [ /[1-9]/, 'DIGIT*' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: '%%FloatConst2930', bnf: [ [ /[0-9]/ ] ], pinned: false },
  { name: '%FloatConst29',
    bnf: [ [ '"."', '%%FloatConst2930+' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'FloatConst',
    bnf: [ [ '"-"?', '%FloatConst28', '%FloatConst29?', 'EXP?' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'DIGIT',
    bnf: [ [ /[0-9]/ ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: '%EXP31',
    bnf: [ [ '"e"' ], [ '"E"' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: '%EXP32',
    bnf: [ [ '"-"' ], [ '"+"' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: '%%EXP3334', bnf: [ [ /[0-9]/ ] ], pinned: false },
  { name: '%EXP33',
    bnf: [ [ '"0"' ], [ /[1-9]/, '%%EXP3334*' ] ],
    fragment: true,
    implicitWs: true,
    simplifyWhenOneChildren: false },
  { name: 'EXP',
    bnf: [ [ '%EXP31', '%EXP32?', '%EXP33' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'StringLiteral',
    bnf: [ [ '\'"\'', 'CHAR*', '\'"\'' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'ESCAPE',
    bnf: [ [ /\x5C/ ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'HEXDIG',
    bnf: [ [ /[a-fA-F0-9]/ ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'ESCAPABLE',
    bnf: 
     [ [ /\x22/ ],
       [ /\x5C/ ],
       [ /\x2F/ ],
       [ /\x62/ ],
       [ /\x66/ ],
       [ /\x6E/ ],
       [ /\x72/ ],
       [ /\x74/ ],
       [ /\x75/, 'HEXDIG', 'HEXDIG', 'HEXDIG', 'HEXDIG' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'CHAR',
    bnf: [ [ 'UNESCAPED' ], [ 'ESCAPE', 'ESCAPABLE' ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false },
  { name: 'UNESCAPED',
    bnf: [ [ /[\x20-\x21]/ ], [ /[\x23-\x5B]/ ], [ /[\x5D-\uFFFF]/ ] ],
    implicitWs: false,
    fragment: false,
    simplifyWhenOneChildren: false } ];